### PR TITLE
Dodao funkciju za dijeljenje

### PR DESCRIPTION
**Pull request by amersabanovic**
This change is [Reviewable](https://reviewable.io/reviews/kenansomun/vvscodereviewproject/3)

### CODE REVIEW

**Comment by KenanSomun** [comment]
___
*[GuessTheNumber/GuessTheNumber/Program.cs, line 29 at r1](https://reviewable.io/reviews/kenansomun/vvscodereviewproject/3#-LPY2HgKD8x_9A5c6B7P:-LPY2HgKD8x_9A5c6B7Q:bockccu) ([raw file](https://github.com/kenansomun/vvscodereviewproject/blob/d35cdb657938e4d043ea10518bafb356c20967ec/GuessTheNumber/GuessTheNumber/Program.cs#L29)):*
> ```Smalltalk
>         }
> 
>         static int Podijeli(int a, int b)
> ```

Funkcija je implementirana fino, no da li će raditi dovoljno precizno obzirom na dijeljenje integera??

**Review by amersabanovic — COMMENTED** [review]
Radi

> *[Reviewable](https://reviewable.io/reviews/kenansomun/vvscodereviewproject/3#-:-LPY2VSE6DQAvRXOnuj2:bb73a8p)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @amersabanovic and @KenanSomun)

___
*[GuessTheNumber/GuessTheNumber/Program.cs, line 29 at r1](https://reviewable.io/reviews/kenansomun/vvscodereviewproject/3#-LPY2HgKD8x_9A5c6B7P:-LPY2iJnA1Q-_YSPbKFm:b-svofhe) ([raw file](https://github.com/kenansomun/vvscodereviewproject/blob/d35cdb657938e4d043ea10518bafb356c20967ec/GuessTheNumber/GuessTheNumber/Program.cs#L29)):*
<details><summary><i>Previously, KenanSomun (Kenan Somun) wrote…</i></summary><blockquote>

Funkcija je implementirana fino, no da li će raditi dovoljno precizno obzirom na dijeljenje integera??
</blockquote></details>

Funkciju prepraviti tako da i to uzme u obzir

**Comment by KenanSomun** [comment]
___
*[GuessTheNumber/GuessTheNumber/Program.cs, line 29 at r1](https://reviewable.io/reviews/kenansomun/vvscodereviewproject/3#-LPY2HgKD8x_9A5c6B7P:-LPY3SU_1buQyoqpkIni:b-lf63as) ([raw file](https://github.com/kenansomun/vvscodereviewproject/blob/d35cdb657938e4d043ea10518bafb356c20967ec/GuessTheNumber/GuessTheNumber/Program.cs#L29)):*
<details><summary><i>Previously, amersabanovic (Amer) wrote…</i></summary><blockquote>

Funkciju prepraviti tako da i to uzme u obzir
</blockquote></details>

Onda je to resolved =))

**Review by KenanSomun — APPROVED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/kenansomun/vvscodereviewproject/3)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request closed without merging**
